# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maptracking', '0004_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre_carrera', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Catalogo_perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Catalogo_perfil',
                'verbose_name_plural': 'Catalogo_perfils',
            },
        ),
        migrations.CreateModel(
            name='Competencia_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Competencia_general',
                'verbose_name_plural': 'Competencia_generals',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField()),
                ('nombre_perfil', models.CharField(max_length=60)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptracking.Carrera')),
                ('catalogo_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptracking.Catalogo_perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfils',
            },
        ),
        migrations.CreateModel(
            name='Unidad_competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=50)),
                ('competencia_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptracking.Competencia_general')),
            ],
            options={
                'verbose_name': 'Unidad_competencia',
                'verbose_name_plural': 'Unidad_competencias',
            },
        ),
        migrations.AddField(
            model_name='competencia_general',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptracking.Perfil'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maptracking.Escuela'),
        ),
    ]
