# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptracking', '0005_auto_20171119_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='maptracking.Categoria', verbose_name='list of Categorias'),
        ),
    ]
