# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptracking', '0008_auto_20171119_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='facultad',
            field=models.CharField(choices=[('Ciencias Empresariales', 'Ciencias Empresariales'), ('Ingenieria y Arquitectura', 'Ingenieria y Arquitectura'), ('Ciencias Humanas y Educacion', 'Ciencias Humanas y Educacion'), ('Ciencias de la Salud', 'Ciencias de la Salud'), ('Teologia', 'Teologia')], default='Ingenieria y Arquitectura', max_length=30),
        ),
    ]
