# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptracking', '0009_auto_20171119_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escuela',
            options={},
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='nombre',
        ),
        migrations.AddField(
            model_name='escuela',
            name='escuela',
            field=models.CharField(choices=[('ani', 'Administracion y Negocios Internacionales'), ('cgt', 'Contabilidad y Gestion Tributaria'), ('mh', 'Medicina Humana'), ('nh', 'Nutricion Humana'), ('enf', 'Enfermeria'), ('ps', 'Psicologia'), ('cc', 'Ciencias de la Comunicacion'), ('eip', 'Educacion de Linguistica e Ingles'), ('ep', 'Educacion Primaria'), ('ema', 'Educacion Musical y Artes'), ('ef', 'Educacion Fisica'), ('emf', 'Educacion Matematica y Fisica'), ('eab', 'Educacion Ambiental, Biologia y Quimica'), ('is', 'Ingenieria de Sistemas'), ('ia', 'Ingenieria Ambiental'), ('iia', 'Ingenieria de Industrias Alimentarias'), ('ic', 'Ingenieria Civil')], default='is', max_length=30),
        ),
    ]
